const OL_SUB_STATS = [
  'ATK',
  'Max Ammo Capacity',
  'Elemental Damage',
  'Hit Rate',
  'Critical Rate',
  'Critical Damage',
  'Charge Speed',
  'Charge Damage',
  'DEF',
  'HP'
];

const EQUIPMENT_SLOTS = ['Head', 'Body', 'Arms', 'Legs'];

const TIER_GRADES = ['SS', 'S', 'A', 'B', 'C', 'D'];

const RARITIES = ['R', 'SR', 'SSR'];
const ELEMENTS = ['Fire', 'Wind', 'Iron', 'Electric', 'Water'];
const CLASSES = ['Attacker', 'Defender', 'Supporter'];
const BURST_TYPES = ['1', '2', '3', 'All'];
const MANUFACTURERS = ['Elysion', 'Missilis', 'Tetra', 'Pilgrim', 'Abnormal'];

const ELEMENT_COLORS = {
  Fire: '#e74c3c',
  Wind: '#2ecc71',
  Iron: '#95a5a6',
  Electric: '#f1c40f',
  Water: '#3498db'
};

const RARITY_COLORS = {
  R: '#8b949e',
  SR: '#3498db',
  SSR: '#f1c40f'
};

const BURST_COLORS = {
  '1': '#e74c3c',
  '2': '#3498db',
  '3': '#2ecc71',
  'All': '#f1c40f'
};

const MANUFACTURER_COLORS = {
  Elysion: '#3498db',
  Missilis: '#e74c3c',
  Tetra: '#f1c40f',
  Pilgrim: '#9b59b6',
  Abnormal: '#2ecc71'
};

const BURST_ICONS = {
  '1': 'assets/burst/1.webp',
  '2': 'assets/burst/2.webp',
  '3': 'assets/burst/3.webp',
  'All': 'assets/burst/3.webp'
};

const ELEMENT_ICONS = {
  Fire: 'assets/elements/fire.webp',
  Wind: 'assets/elements/wind.webp',
  Iron: 'assets/elements/iron.webp',
  Electric: 'assets/elements/electric.webp',
  Water: 'assets/elements/water.webp'
};

const MANUFACTURER_ICONS = {
  Elysion: 'assets/manufacturers/elysion.webp',
  Missilis: 'assets/manufacturers/missilis.webp',
  Tetra: 'assets/manufacturers/tetra.webp',
  Pilgrim: 'assets/manufacturers/pilgrim.webp',
  Abnormal: 'assets/manufacturers/abnormal.webp'
};

function defaultCharData() {
  const eq = {};
  EQUIPMENT_SLOTS.forEach(s => {
    eq[s] = { equipped: 'none', overloaded: false, olSubStats: [] };
  });
  return {
    owned: false,
    coreLevel: 0,
    skill1: 1,
    skill2: 1,
    burstSkill: 1,
    hasCollectionItem: false,
    tierStory: null,
    tierBossing: null,
    tierPvp: null,
    equipment: eq
  };
}

const CHARACTERS = [
  {unitId: 99, name: "2B", icon: "assets/icons/99.webp", rarity: "SSR", element: "Fire", weapon: "Assault Rifle", class: "Defender", burstType: "3", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 100, name: "A2", icon: "assets/icons/100.webp", rarity: "SSR", element: "Fire", weapon: "Rocket Launcher", class: "Attacker", burstType: "3", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 185, name: "Ada Wong", icon: "assets/icons/185.webp", rarity: "SSR", element: "Electric", weapon: "Rocket Launcher", class: "Attacker", burstType: "3", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 76, name: "Ade", icon: "assets/icons/76.webp", rarity: "SSR", element: "Wind", weapon: "Assault Rifle", class: "Supporter", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 182, name: "Ade: Agent Bunny", icon: "assets/icons/182.webp", rarity: "SSR", element: "Iron", weapon: "Sniper Rifle", class: "Supporter", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 17, name: "Admi", icon: "assets/icons/17.webp", rarity: "SSR", element: "Wind", weapon: "Sniper Rifle", class: "Supporter", burstType: "2", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 19, name: "Alice", icon: "assets/icons/19.webp", rarity: "SSR", element: "Fire", weapon: "Sniper Rifle", class: "Attacker", burstType: "3", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 125, name: "Alice: Wonderland Bunny", icon: "assets/icons/125.webp", rarity: "SSR", element: "Water", weapon: "SMG", class: "Supporter", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 98, name: "Anchor", icon: "assets/icons/98.webp", rarity: "SR", element: "Wind", weapon: "Rocket Launcher", class: "Defender", burstType: "1", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 148, name: "Anchor: Innocent Maid", icon: "assets/icons/148.webp", rarity: "SSR", element: "Water", weapon: "Rocket Launcher", class: "Supporter", burstType: "2", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 39, name: "Anis", icon: "assets/icons/39.webp", rarity: "SR", element: "Iron", weapon: "Rocket Launcher", class: "Defender", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 96, name: "Anis: Sparkling Summer", icon: "assets/icons/96.webp", rarity: "SSR", element: "Electric", weapon: "Shotgun", class: "Supporter", burstType: "3", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 67, name: "Anne: Miracle Fairy", icon: "assets/icons/67.webp", rarity: "SSR", element: "Wind", weapon: "Rocket Launcher", class: "Supporter", burstType: "2", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 167, name: "Arcana", icon: "assets/icons/167.webp", rarity: "SSR", element: "Electric", weapon: "Rocket Launcher", class: "Supporter", burstType: "2", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 205, name: "Arcana: Fortune Mate", icon: "assets/icons/205.webp", rarity: "SSR", element: "Fire", weapon: "Shotgun", class: "Attacker", burstType: "2", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 25, name: "Aria", icon: "assets/icons/25.webp", rarity: "SSR", element: "Water", weapon: "Minigun", class: "Attacker", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 131, name: "Asuka Shikinami Langley", icon: "assets/icons/131.webp", rarity: "SSR", element: "Fire", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 150, name: "Asuka Shikinami Langley: Wille", icon: "assets/icons/150.webp", rarity: "SSR", element: "Wind", weapon: "Minigun", class: "Attacker", burstType: "3", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 120, name: "Bay", icon: "assets/icons/120.webp", rarity: "SSR", element: "Fire", weapon: "Rocket Launcher", class: "Defender", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 178, name: "Bay (Treasure)", icon: "assets/icons/178.webp", rarity: "SSR", element: "Fire", weapon: "Rocket Launcher", class: "Defender", burstType: "2", manufacturer: "Tetra", hasTreasure: true},
  {unitId: 40, name: "Belorta", icon: "assets/icons/40.webp", rarity: "SR", element: "Electric", weapon: "Rocket Launcher", class: "Attacker", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 80, name: "Biscuit", icon: "assets/icons/80.webp", rarity: "SSR", element: "Electric", weapon: "Rocket Launcher", class: "Supporter", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 86, name: "Blanc", icon: "assets/icons/86.webp", rarity: "SSR", element: "Wind", weapon: "Assault Rifle", class: "Defender", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 162, name: "Bready", icon: "assets/icons/162.webp", rarity: "SSR", element: "Water", weapon: "Sniper Rifle", class: "Attacker", burstType: "3", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 6, name: "Brid", icon: "assets/icons/6.webp", rarity: "SSR", element: "Water", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 192, name: "Brid: Silent Track", icon: "assets/icons/192.webp", rarity: "SSR", element: "Fire", weapon: "Shotgun", class: "Supporter", burstType: "2", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 14, name: "Centi", icon: "assets/icons/14.webp", rarity: "SSR", element: "Iron", weapon: "Rocket Launcher", class: "Defender", burstType: "2", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 199, name: "Centi (Treasure)", icon: "assets/icons/199.webp", rarity: "SSR", element: "Iron", weapon: "Rocket Launcher", class: "Defender", burstType: "2", manufacturer: "Missilis", hasTreasure: true},
  {unitId: 190, name: "Chime", icon: "assets/icons/190.webp", rarity: "SSR", element: "Iron", weapon: "SMG", class: "Supporter", burstType: "2", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 201, name: "Chisato Nishikigi", icon: "assets/icons/201.webp", rarity: "SSR", element: "Iron", weapon: "SMG", class: "Attacker", burstType: "3", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 139, name: "Cinderella", icon: "assets/icons/139.webp", rarity: "SSR", element: "Electric", weapon: "Rocket Launcher", class: "Defender", burstType: "3", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 186, name: "Claire Redfield", icon: "assets/icons/186.webp", rarity: "SR", element: "Electric", weapon: "Rocket Launcher", class: "Supporter", burstType: "1", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 126, name: "Clay", icon: "assets/icons/126.webp", rarity: "SSR", element: "Electric", weapon: "SMG", class: "Supporter", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 74, name: "Cocoa", icon: "assets/icons/74.webp", rarity: "SSR", element: "Fire", weapon: "Sniper Rifle", class: "Supporter", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 16, name: "Crow", icon: "assets/icons/16.webp", rarity: "SSR", element: "Fire", weapon: "SMG", class: "Defender", burstType: "3", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 121, name: "Crown", icon: "assets/icons/121.webp", rarity: "SSR", element: "Iron", weapon: "Minigun", class: "Defender", burstType: "2", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 163, name: "Crust", icon: "assets/icons/163.webp", rarity: "SSR", element: "Water", weapon: "Rocket Launcher", class: "Supporter", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 83, name: "D", icon: "assets/icons/83.webp", rarity: "SSR", element: "Wind", weapon: "SMG", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 116, name: "D: Killer Wife", icon: "assets/icons/116.webp", rarity: "SSR", element: "Fire", weapon: "Sniper Rifle", class: "Supporter", burstType: "1", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 35, name: "Delta", icon: "assets/icons/35.webp", rarity: "SR", element: "Wind", weapon: "Sniper Rifle", class: "Defender", burstType: "2", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 187, name: "Delta: Ninja Thief", icon: "assets/icons/187.webp", rarity: "SSR", element: "Water", weapon: "Minigun", class: "Defender", burstType: "2", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 8, name: "Diesel", icon: "assets/icons/8.webp", rarity: "SSR", element: "Wind", weapon: "Minigun", class: "Defender", burstType: "2", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 149, name: "Diesel (Treasure)", icon: "assets/icons/149.webp", rarity: "SSR", element: "Wind", weapon: "Minigun", class: "Defender", burstType: "2", manufacturer: "Elysion", hasTreasure: true},
  {unitId: 193, name: "Diesel: Winter Sweets", icon: "assets/icons/193.webp", rarity: "SSR", element: "Fire", weapon: "Rocket Launcher", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 43, name: "Dolla", icon: "assets/icons/43.webp", rarity: "SSR", element: "Wind", weapon: "Sniper Rifle", class: "Supporter", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 84, name: "Dorothy", icon: "assets/icons/84.webp", rarity: "SSR", element: "Water", weapon: "Assault Rifle", class: "Supporter", burstType: "1", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 173, name: "Dorothy: Serendipity", icon: "assets/icons/173.webp", rarity: "SSR", element: "Water", weapon: "Shotgun", class: "Attacker", burstType: "3", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 15, name: "Drake", icon: "assets/icons/15.webp", rarity: "SSR", element: "Fire", weapon: "Shotgun", class: "Attacker", burstType: "3", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 159, name: "Drake (Treasure)", icon: "assets/icons/159.webp", rarity: "SSR", element: "Fire", weapon: "Shotgun", class: "Attacker", burstType: "3", manufacturer: "Missilis", hasTreasure: true},
  {unitId: 204, name: "E.H.", icon: "assets/icons/204.webp", rarity: "SSR", element: "Wind", weapon: "SMG", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 129, name: "Ein", icon: "assets/icons/129.webp", rarity: "SSR", element: "Electric", weapon: "Sniper Rifle", class: "Attacker", burstType: "3", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 115, name: "Elegg", icon: "assets/icons/115.webp", rarity: "SSR", element: "Electric", weapon: "Minigun", class: "Supporter", burstType: "2", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 174, name: "Elegg: Boom and Shock", icon: "assets/icons/174.webp", rarity: "SSR", element: "Water", weapon: "Minigun", class: "Attacker", burstType: "3", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 117, name: "Emilia", icon: "assets/icons/117.webp", rarity: "SSR", element: "Water", weapon: "Rocket Launcher", class: "Attacker", burstType: "3", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 1, name: "Emma", icon: "assets/icons/1.webp", rarity: "SSR", element: "Fire", weapon: "Minigun", class: "Supporter", burstType: "1", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 179, name: "Emma: Tactical Upgrade", icon: "assets/icons/179.webp", rarity: "SSR", element: "Fire", weapon: "Minigun", class: "Supporter", burstType: "1", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 24, name: "Epinel", icon: "assets/icons/24.webp", rarity: "SSR", element: "Wind", weapon: "SMG", class: "Attacker", burstType: "3", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 38, name: "Ether", icon: "assets/icons/38.webp", rarity: "SR", element: "Electric", weapon: "Shotgun", class: "Defender", burstType: "1", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 9, name: "Eunhwa", icon: "assets/icons/9.webp", rarity: "SSR", element: "Fire", weapon: "Sniper Rifle", class: "Attacker", burstType: "2", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 180, name: "Eunhwa: Tactical Upgrade", icon: "assets/icons/180.webp", rarity: "SSR", element: "Fire", weapon: "Sniper Rifle", class: "Attacker", burstType: "2", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 170, name: "Eve", icon: "assets/icons/170.webp", rarity: "SSR", element: "Iron", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 32, name: "Exia", icon: "assets/icons/32.webp", rarity: "SSR", element: "Electric", weapon: "Sniper Rifle", class: "Supporter", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 153, name: "Exia (Treasure)", icon: "assets/icons/153.webp", rarity: "SSR", element: "Electric", weapon: "Sniper Rifle", class: "Supporter", burstType: "1", manufacturer: "Tetra", hasTreasure: true},
  {unitId: 142, name: "Flora", icon: "assets/icons/142.webp", rarity: "SSR", element: "Electric", weapon: "Minigun", class: "Supporter", burstType: "2", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 42, name: "Folkwang", icon: "assets/icons/42.webp", rarity: "SSR", element: "Water", weapon: "Assault Rifle", class: "Defender", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 20, name: "Frima", icon: "assets/icons/20.webp", rarity: "SSR", element: "Iron", weapon: "Sniper Rifle", class: "Supporter", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 154, name: "Frima (Treasure)", icon: "assets/icons/154.webp", rarity: "SSR", element: "Iron", weapon: "Sniper Rifle", class: "Supporter", burstType: "1", manufacturer: "Tetra", hasTreasure: true},
  {unitId: 140, name: "Grave", icon: "assets/icons/140.webp", rarity: "SSR", element: "Fire", weapon: "Assault Rifle", class: "Supporter", burstType: "2", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 10, name: "Guillotine", icon: "assets/icons/10.webp", rarity: "SSR", element: "Electric", weapon: "Minigun", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 144, name: "Guillotine: Winter Slayer", icon: "assets/icons/144.webp", rarity: "SSR", element: "Water", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 72, name: "Guilty", icon: "assets/icons/72.webp", rarity: "SSR", element: "Wind", weapon: "Shotgun", class: "Attacker", burstType: "2", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 30, name: "Harran", icon: "assets/icons/30.webp", rarity: "SSR", element: "Electric", weapon: "Sniper Rifle", class: "Attacker", burstType: "3", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 47, name: "Helm", icon: "assets/icons/47.webp", rarity: "SSR", element: "Water", weapon: "Sniper Rifle", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 157, name: "Helm (Treasure)", icon: "assets/icons/157.webp", rarity: "SSR", element: "Water", weapon: "Sniper Rifle", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: true},
  {unitId: 97, name: "Helm: Aquamarine", icon: "assets/icons/97.webp", rarity: "SSR", element: "Iron", weapon: "Assault Rifle", class: "Attacker", burstType: "2", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 79, name: "Himeno", icon: "assets/icons/79.webp", rarity: "SR", element: "Wind", weapon: "Sniper Rifle", class: "Supporter", burstType: "2", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 56, name: "iDoll Flower", icon: "assets/icons/56.webp", rarity: "R", element: "Wind", weapon: "Rocket Launcher", class: "Defender", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 57, name: "iDoll Ocean", icon: "assets/icons/57.webp", rarity: "R", element: "Water", weapon: "SMG", class: "Supporter", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 62, name: "iDoll Sun", icon: "assets/icons/62.webp", rarity: "R", element: "Iron", weapon: "Assault Rifle", class: "Supporter", burstType: "3", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 44, name: "Isabel", icon: "assets/icons/44.webp", rarity: "SSR", element: "Electric", weapon: "Shotgun", class: "Attacker", burstType: "3", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 69, name: "Jackal", icon: "assets/icons/69.webp", rarity: "SSR", element: "Iron", weapon: "Rocket Launcher", class: "Defender", burstType: "1", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 184, name: "Jill Valentine", icon: "assets/icons/184.webp", rarity: "SSR", element: "Electric", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 13, name: "Julia", icon: "assets/icons/13.webp", rarity: "SSR", element: "Iron", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 177, name: "Julia (Treasure)", icon: "assets/icons/177.webp", rarity: "SSR", element: "Iron", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Missilis", hasTreasure: true},
  {unitId: 168, name: "K", icon: "assets/icons/168.webp", rarity: "SSR", element: "Electric", weapon: "SMG", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 122, name: "Kilo", icon: "assets/icons/122.webp", rarity: "SSR", element: "Fire", weapon: "Minigun", class: "Defender", burstType: "3", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 203, name: "Kurumi", icon: "assets/icons/203.webp", rarity: "SR", element: "Iron", weapon: "Assault Rifle", class: "Supporter", burstType: "1", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 195, name: "Label", icon: "assets/icons/195.webp", rarity: "SSR", element: "Iron", weapon: "Assault Rifle", class: "Defender", burstType: "1", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 46, name: "Laplace", icon: "assets/icons/46.webp", rarity: "SSR", element: "Iron", weapon: "Rocket Launcher", class: "Attacker", burstType: "3", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 156, name: "Laplace (Treasure)", icon: "assets/icons/156.webp", rarity: "SSR", element: "Iron", weapon: "Rocket Launcher", class: "Attacker", burstType: "3", manufacturer: "Missilis", hasTreasure: true},
  {unitId: 112, name: "Leona", icon: "assets/icons/112.webp", rarity: "SSR", element: "Water", weapon: "Shotgun", class: "Supporter", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 189, name: "Liberalio", icon: "assets/icons/189.webp", rarity: "SSR", element: "Wind", weapon: "Sniper Rifle", class: "Attacker", burstType: "3", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 169, name: "Lily", icon: "assets/icons/169.webp", rarity: "SR", element: "Wind", weapon: "SMG", class: "Supporter", burstType: "2", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 45, name: "Liter", icon: "assets/icons/45.webp", rarity: "SSR", element: "Iron", weapon: "SMG", class: "Supporter", burstType: "1", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 164, name: "Little Mermaid (Siren)", icon: "assets/icons/164.webp", rarity: "SSR", element: "Wind", weapon: "SMG", class: "Supporter", burstType: "1", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 22, name: "Ludmilla", icon: "assets/icons/22.webp", rarity: "SSR", element: "Water", weapon: "SMG", class: "Defender", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 108, name: "Ludmilla: Winter Owner", icon: "assets/icons/108.webp", rarity: "SSR", element: "Water", weapon: "Minigun", class: "Attacker", burstType: "3", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 48, name: "Maiden", icon: "assets/icons/48.webp", rarity: "SSR", element: "Electric", weapon: "Shotgun", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 143, name: "Maiden: Ice Rose", icon: "assets/icons/143.webp", rarity: "SSR", element: "Electric", weapon: "Rocket Launcher", class: "Defender", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 78, name: "Makima", icon: "assets/icons/78.webp", rarity: "SSR", element: "Water", weapon: "SMG", class: "Defender", burstType: "2", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 146, name: "Mana", icon: "assets/icons/146.webp", rarity: "SSR", element: "Wind", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 102, name: "Marciana", icon: "assets/icons/102.webp", rarity: "SSR", element: "Iron", weapon: "Shotgun", class: "Supporter", burstType: "2", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 133, name: "Mari Makinami Illustrious", icon: "assets/icons/133.webp", rarity: "SSR", element: "Electric", weapon: "Sniper Rifle", class: "Supporter", burstType: "2", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 21, name: "Mary", icon: "assets/icons/21.webp", rarity: "SSR", element: "Water", weapon: "Shotgun", class: "Supporter", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 89, name: "Mary: Bay Goddess", icon: "assets/icons/89.webp", rarity: "SSR", element: "Water", weapon: "Sniper Rifle", class: "Supporter", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 92, name: "Mast", icon: "assets/icons/92.webp", rarity: "SSR", element: "Electric", weapon: "SMG", class: "Supporter", burstType: "2", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 147, name: "Mast: Romantic Maid", icon: "assets/icons/147.webp", rarity: "SSR", element: "Water", weapon: "Minigun", class: "Supporter", burstType: "2", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 11, name: "Maxwell", icon: "assets/icons/11.webp", rarity: "SSR", element: "Iron", weapon: "Sniper Rifle", class: "Attacker", burstType: "3", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 41, name: "Mica", icon: "assets/icons/41.webp", rarity: "SR", element: "Wind", weapon: "Rocket Launcher", class: "Supporter", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 110, name: "Mica: Snow Buddy", icon: "assets/icons/110.webp", rarity: "SSR", element: "Iron", weapon: "SMG", class: "Supporter", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 36, name: "Mihara", icon: "assets/icons/36.webp", rarity: "SR", element: "Water", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 165, name: "Mihara: Bonding Chain", icon: "assets/icons/165.webp", rarity: "SSR", element: "Fire", weapon: "Minigun", class: "Attacker", burstType: "3", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 49, name: "Milk", icon: "assets/icons/49.webp", rarity: "SSR", element: "Water", weapon: "Sniper Rifle", class: "Attacker", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 158, name: "Milk (Treasure)", icon: "assets/icons/158.webp", rarity: "SSR", element: "Water", weapon: "Sniper Rifle", class: "Attacker", burstType: "1", manufacturer: "Tetra", hasTreasure: true},
  {unitId: 183, name: "Milk: Blooming Bunny", icon: "assets/icons/183.webp", rarity: "SSR", element: "Iron", weapon: "Sniper Rifle", class: "Attacker", burstType: "3", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 5, name: "Miranda", icon: "assets/icons/5.webp", rarity: "SSR", element: "Fire", weapon: "SMG", class: "Supporter", burstType: "1", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 160, name: "Miranda (Treasure)", icon: "assets/icons/160.webp", rarity: "SSR", element: "Fire", weapon: "SMG", class: "Supporter", burstType: "1", manufacturer: "Elysion", hasTreasure: true},
  {unitId: 134, name: "Misato Katsuragi", icon: "assets/icons/134.webp", rarity: "SR", element: "Iron", weapon: "SMG", class: "Supporter", burstType: "1", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 68, name: "Modernia", icon: "assets/icons/68.webp", rarity: "SSR", element: "Fire", weapon: "Minigun", class: "Attacker", burstType: "3", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 113, name: "Moran", icon: "assets/icons/113.webp", rarity: "SSR", element: "Electric", weapon: "Assault Rifle", class: "Defender", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 197, name: "Moran (Treasure)", icon: "assets/icons/197.webp", rarity: "SSR", element: "Electric", weapon: "Assault Rifle", class: "Defender", burstType: "1", manufacturer: "Tetra", hasTreasure: true},
  {unitId: 166, name: "Mori", icon: "assets/icons/166.webp", rarity: "SSR", element: "Wind", weapon: "Assault Rifle", class: "Defender", burstType: "2", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 37, name: "N102", icon: "assets/icons/37.webp", rarity: "SR", element: "Water", weapon: "Rocket Launcher", class: "Supporter", burstType: "1", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 103, name: "Naga", icon: "assets/icons/103.webp", rarity: "SSR", element: "Electric", weapon: "Shotgun", class: "Supporter", burstType: "2", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 188, name: "Nayuta", icon: "assets/icons/188.webp", rarity: "SSR", element: "Wind", weapon: "SMG", class: "Supporter", burstType: "2", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 34, name: "Neon", icon: "assets/icons/34.webp", rarity: "SR", element: "Fire", weapon: "Shotgun", class: "Supporter", burstType: "1", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 90, name: "Neon: Blue Ocean", icon: "assets/icons/90.webp", rarity: "SSR", element: "Water", weapon: "Minigun", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 91, name: "Nero", icon: "assets/icons/91.webp", rarity: "SSR", element: "Fire", weapon: "SMG", class: "Defender", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 65, name: "Neve", icon: "assets/icons/65.webp", rarity: "SR", element: "Water", weapon: "Shotgun", class: "Attacker", burstType: "3", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 81, name: "Nihilister", icon: "assets/icons/81.webp", rarity: "SSR", element: "Fire", weapon: "Sniper Rifle", class: "Attacker", burstType: "2", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 31, name: "Noah", icon: "assets/icons/31.webp", rarity: "SSR", element: "Wind", weapon: "Rocket Launcher", class: "Defender", burstType: "2", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 87, name: "Noir", icon: "assets/icons/87.webp", rarity: "SSR", element: "Wind", weapon: "Shotgun", class: "Attacker", burstType: "3", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 26, name: "Noise", icon: "assets/icons/26.webp", rarity: "SSR", element: "Electric", weapon: "Rocket Launcher", class: "Supporter", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 50, name: "Novel", icon: "assets/icons/50.webp", rarity: "SSR", element: "Iron", weapon: "SMG", class: "Defender", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 101, name: "Pascal", icon: "assets/icons/101.webp", rarity: "SR", element: "Iron", weapon: "Rocket Launcher", class: "Supporter", burstType: "1", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 51, name: "Pepper", icon: "assets/icons/51.webp", rarity: "SSR", element: "Wind", weapon: "Shotgun", class: "Supporter", burstType: "1", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 137, name: "Phantom", icon: "assets/icons/137.webp", rarity: "SSR", element: "Water", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 4, name: "Poli", icon: "assets/icons/4.webp", rarity: "SSR", element: "Water", weapon: "Shotgun", class: "Defender", burstType: "2", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 175, name: "Poli (Treasure)", icon: "assets/icons/175.webp", rarity: "SSR", element: "Water", weapon: "Shotgun", class: "Defender", burstType: "2", manufacturer: "Elysion", hasTreasure: true},
  {unitId: 77, name: "Power", icon: "assets/icons/77.webp", rarity: "SSR", element: "Fire", weapon: "Rocket Launcher", class: "Attacker", burstType: "3", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 2, name: "Privaty", icon: "assets/icons/2.webp", rarity: "SSR", element: "Water", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 198, name: "Privaty (Treasure)", icon: "assets/icons/198.webp", rarity: "SSR", element: "Water", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: true},
  {unitId: 114, name: "Privaty: Unkind Maid", icon: "assets/icons/114.webp", rarity: "SSR", element: "Electric", weapon: "Shotgun", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 58, name: "Product 08", icon: "assets/icons/58.webp", rarity: "R", element: "Electric", weapon: "Sniper Rifle", class: "Supporter", burstType: "1", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 63, name: "Product 12", icon: "assets/icons/63.webp", rarity: "R", element: "Fire", weapon: "Minigun", class: "Attacker", burstType: "3", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 60, name: "Product 23", icon: "assets/icons/60.webp", rarity: "R", element: "Wind", weapon: "Shotgun", class: "Supporter", burstType: "2", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 73, name: "Quency", icon: "assets/icons/73.webp", rarity: "SSR", element: "Electric", weapon: "SMG", class: "Supporter", burstType: "2", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 136, name: "Quency: Escape Queen", icon: "assets/icons/136.webp", rarity: "SSR", element: "Water", weapon: "SMG", class: "Attacker", burstType: "3", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 105, name: "Quiry", icon: "assets/icons/105.webp", rarity: "SSR", element: "Wind", weapon: "Rocket Launcher", class: "Supporter", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 119, name: "Ram", icon: "assets/icons/119.webp", rarity: "SR", element: "Wind", weapon: "Sniper Rifle", class: "Defender", burstType: "1", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 33, name: "Rapi", icon: "assets/icons/33.webp", rarity: "SR", element: "Fire", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 145, name: "Rapi: Red Hood", icon: "assets/icons/145.webp", rarity: "SSR", element: "Fire", weapon: "Minigun", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 52, name: "Rapunzel", icon: "assets/icons/52.webp", rarity: "SSR", element: "Iron", weapon: "Rocket Launcher", class: "Supporter", burstType: "1", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 141, name: "Rapunzel: Pure Grace", icon: "assets/icons/141.webp", rarity: "SSR", element: "Iron", weapon: "Sniper Rifle", class: "Defender", burstType: "1", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 171, name: "Raven", icon: "assets/icons/171.webp", rarity: "SSR", element: "Iron", weapon: "Rocket Launcher", class: "Attacker", burstType: "3", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 109, name: "Red Hood", icon: "assets/icons/109.webp", rarity: "SSR", element: "Iron", weapon: "Sniper Rifle", class: "Attacker", burstType: "All", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 85, name: "Rei", icon: "assets/icons/85.webp", rarity: "SSR", element: "Water", weapon: "SMG", class: "Defender", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 132, name: "Rei Ayanami", icon: "assets/icons/132.webp", rarity: "SSR", element: "Fire", weapon: "Minigun", class: "Attacker", burstType: "3", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 151, name: "Rei Ayanami (Tentative Name)", icon: "assets/icons/151.webp", rarity: "SSR", element: "Wind", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 118, name: "Rem", icon: "assets/icons/118.webp", rarity: "SSR", element: "Water", weapon: "Minigun", class: "Supporter", burstType: "2", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 88, name: "Rosanna", icon: "assets/icons/88.webp", rarity: "SSR", element: "Electric", weapon: "Minigun", class: "Attacker", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 128, name: "Rosanna: Chic Ocean", icon: "assets/icons/128.webp", rarity: "SSR", element: "Wind", weapon: "Assault Rifle", class: "Supporter", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 135, name: "Rouge", icon: "assets/icons/135.webp", rarity: "SSR", element: "Electric", weapon: "Sniper Rifle", class: "Supporter", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 138, name: "Rumani", icon: "assets/icons/138.webp", rarity: "SSR", element: "Fire", weapon: "Rocket Launcher", class: "Defender", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 53, name: "Rupee", icon: "assets/icons/53.webp", rarity: "SSR", element: "Iron", weapon: "Assault Rifle", class: "Attacker", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 66, name: "Rupee: Winter Shopper", icon: "assets/icons/66.webp", rarity: "SSR", element: "Electric", weapon: "Assault Rifle", class: "Defender", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 82, name: "Sakura", icon: "assets/icons/82.webp", rarity: "SSR", element: "Fire", weapon: "Sniper Rifle", class: "Supporter", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 152, name: "Sakura Suzuhara", icon: "assets/icons/152.webp", rarity: "SR", element: "Water", weapon: "SMG", class: "Supporter", burstType: "1", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 127, name: "Sakura: Bloom in Summer", icon: "assets/icons/127.webp", rarity: "SSR", element: "Wind", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 29, name: "Scarlet", icon: "assets/icons/29.webp", rarity: "SSR", element: "Electric", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 111, name: "Scarlet: Black Shadow", icon: "assets/icons/111.webp", rarity: "SSR", element: "Wind", weapon: "Rocket Launcher", class: "Attacker", burstType: "3", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 3, name: "Signal", icon: "assets/icons/3.webp", rarity: "SSR", element: "Fire", weapon: "SMG", class: "Attacker", burstType: "2", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 71, name: "Sin", icon: "assets/icons/71.webp", rarity: "SSR", element: "Electric", weapon: "Assault Rifle", class: "Defender", burstType: "2", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 28, name: "Snow White", icon: "assets/icons/28.webp", rarity: "SSR", element: "Iron", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 194, name: "Snow White: Heavy Arms", icon: "assets/icons/194.webp", rarity: "SSR", element: "Water", weapon: "Sniper Rifle", class: "Attacker", burstType: "3", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 106, name: "Snow White: Innocent Days", icon: "assets/icons/106.webp", rarity: "SSR", element: "Iron", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 75, name: "Soda", icon: "assets/icons/75.webp", rarity: "SSR", element: "Fire", weapon: "Minigun", class: "Supporter", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 124, name: "Soda: Twinkling Bunny", icon: "assets/icons/124.webp", rarity: "SSR", element: "Iron", weapon: "Shotgun", class: "Attacker", burstType: "3", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 64, name: "Soldier EG", icon: "assets/icons/64.webp", rarity: "R", element: "Electric", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 61, name: "Soldier FA", icon: "assets/icons/61.webp", rarity: "R", element: "Iron", weapon: "Shotgun", class: "Defender", burstType: "2", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 59, name: "Soldier OW", icon: "assets/icons/59.webp", rarity: "R", element: "Fire", weapon: "SMG", class: "Supporter", burstType: "1", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 7, name: "Soline", icon: "assets/icons/7.webp", rarity: "SSR", element: "Iron", weapon: "SMG", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 191, name: "Soline: Frost Ticket", icon: "assets/icons/191.webp", rarity: "SSR", element: "Water", weapon: "Shotgun", class: "Supporter", burstType: "1", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 172, name: "Sora", icon: "assets/icons/172.webp", rarity: "SSR", element: "Wind", weapon: "Rocket Launcher", class: "Supporter", burstType: "1", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 18, name: "Sugar", icon: "assets/icons/18.webp", rarity: "SSR", element: "Iron", weapon: "Shotgun", class: "Attacker", burstType: "3", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 202, name: "Takina Inoue", icon: "assets/icons/202.webp", rarity: "SSR", element: "Iron", weapon: "Sniper Rifle", class: "Supporter", burstType: "2", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 104, name: "Tia", icon: "assets/icons/104.webp", rarity: "SSR", element: "Iron", weapon: "Rocket Launcher", class: "Defender", burstType: "1", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 107, name: "Tove", icon: "assets/icons/107.webp", rarity: "SSR", element: "Water", weapon: "Assault Rifle", class: "Supporter", burstType: "1", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 176, name: "Tove (Treasure)", icon: "assets/icons/176.webp", rarity: "SSR", element: "Water", weapon: "Assault Rifle", class: "Supporter", burstType: "1", manufacturer: "Missilis", hasTreasure: true},
  {unitId: 161, name: "Trina", icon: "assets/icons/161.webp", rarity: "SSR", element: "Electric", weapon: "Rocket Launcher", class: "Supporter", burstType: "2", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 123, name: "Trony", icon: "assets/icons/123.webp", rarity: "SSR", element: "Fire", weapon: "Sniper Rifle", class: "Attacker", burstType: "3", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 196, name: "Velvet", icon: "assets/icons/196.webp", rarity: "SSR", element: "Wind", weapon: "Sniper Rifle", class: "Supporter", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 54, name: "Vesti", icon: "assets/icons/54.webp", rarity: "SSR", element: "Water", weapon: "Rocket Launcher", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 181, name: "Vesti: Tactical Upgrade", icon: "assets/icons/181.webp", rarity: "SSR", element: "Fire", weapon: "Rocket Launcher", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 70, name: "Viper", icon: "assets/icons/70.webp", rarity: "SSR", element: "Water", weapon: "Shotgun", class: "Attacker", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 155, name: "Viper (Treasure)", icon: "assets/icons/155.webp", rarity: "SSR", element: "Water", weapon: "Shotgun", class: "Attacker", burstType: "2", manufacturer: "Tetra", hasTreasure: true},
  {unitId: 27, name: "Volume", icon: "assets/icons/27.webp", rarity: "SSR", element: "Wind", weapon: "SMG", class: "Attacker", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 23, name: "Yan", icon: "assets/icons/23.webp", rarity: "SSR", element: "Fire", weapon: "Rocket Launcher", class: "Supporter", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 55, name: "Yulha", icon: "assets/icons/55.webp", rarity: "SSR", element: "Fire", weapon: "Sniper Rifle", class: "Attacker", burstType: "3", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 12, name: "Yuni", icon: "assets/icons/12.webp", rarity: "SSR", element: "Fire", weapon: "Rocket Launcher", class: "Defender", burstType: "2", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 130, name: "Zwei", icon: "assets/icons/130.webp", rarity: "SSR", element: "Electric", weapon: "Shotgun", class: "Supporter", burstType: "1", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 200, name: "Zwei (Treasure)", icon: "assets/icons/200.webp", rarity: "SSR", element: "Electric", weapon: "Shotgun", class: "Supporter", burstType: "1", manufacturer: "Elysion", hasTreasure: true}
];
