const OL_SUB_STATS = [
  'ATK',
  'Max Ammo Capacity',
  'Elemental Damage',
  'Hit Rate',
  'Critical Rate',
  'Critical Damage',
  'Charge Speed',
  'Charge Damage',
  'DEF',
  'HP'
];

const EQUIPMENT_SLOTS = ['Head', 'Body', 'Arms', 'Legs'];

const TIER_GRADES = ['SS', 'S', 'A', 'B', 'C', 'D'];

const RARITIES = ['R', 'SR', 'SSR'];
const ELEMENTS = ['Fire', 'Wind', 'Iron', 'Electric', 'Water'];
const CLASSES = ['Attacker', 'Defender', 'Supporter'];
const BURST_TYPES = ['1', '2', '3', 'All'];
const MANUFACTURERS = ['Elysion', 'Missilis', 'Tetra', 'Pilgrim', 'Abnormal'];

const ELEMENT_COLORS = {
  Fire: '#e74c3c',
  Wind: '#2ecc71',
  Iron: '#95a5a6',
  Electric: '#f1c40f',
  Water: '#3498db'
};

const RARITY_COLORS = {
  R: '#8b949e',
  SR: '#3498db',
  SSR: '#f1c40f'
};

const BURST_COLORS = {
  '1': '#e74c3c',
  '2': '#3498db',
  '3': '#2ecc71',
  'All': '#f1c40f'
};

const MANUFACTURER_COLORS = {
  Elysion: '#3498db',
  Missilis: '#e74c3c',
  Tetra: '#f1c40f',
  Pilgrim: '#9b59b6',
  Abnormal: '#2ecc71'
};

function defaultCharData() {
  const eq = {};
  EQUIPMENT_SLOTS.forEach(s => {
    eq[s] = { equipped: 'none', overloaded: false, olSubStats: [] };
  });
  return {
    owned: false,
    coreLevel: 0,
    skill1: 1,
    skill2: 1,
    burstSkill: 1,
    hasCollectionItem: false,
    tierStory: null,
    tierBossing: null,
    tierPvp: null,
    equipment: eq
  };
}

const CHARACTERS = [
  {unitId: 99, name: "2B", rarity: "SSR", element: "Fire", weapon: "Assault Rifle", class: "Defender", burstType: "3", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 100, name: "A2", rarity: "SSR", element: "Fire", weapon: "Rocket Launcher", class: "Attacker", burstType: "3", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 185, name: "Ada Wong", rarity: "SSR", element: "Electric", weapon: "Rocket Launcher", class: "Attacker", burstType: "3", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 76, name: "Ade", rarity: "SSR", element: "Wind", weapon: "Assault Rifle", class: "Supporter", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 182, name: "Ade: Agent Bunny", rarity: "SSR", element: "Iron", weapon: "Sniper Rifle", class: "Supporter", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 17, name: "Admi", rarity: "SSR", element: "Wind", weapon: "Sniper Rifle", class: "Supporter", burstType: "2", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 19, name: "Alice", rarity: "SSR", element: "Fire", weapon: "Sniper Rifle", class: "Attacker", burstType: "3", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 125, name: "Alice: Wonderland Bunny", rarity: "SSR", element: "Water", weapon: "SMG", class: "Supporter", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 98, name: "Anchor", rarity: "SR", element: "Wind", weapon: "Rocket Launcher", class: "Defender", burstType: "1", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 148, name: "Anchor: Innocent Maid", rarity: "SSR", element: "Water", weapon: "Rocket Launcher", class: "Supporter", burstType: "2", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 39, name: "Anis", rarity: "SR", element: "Iron", weapon: "Rocket Launcher", class: "Defender", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 96, name: "Anis: Sparkling Summer", rarity: "SSR", element: "Electric", weapon: "Shotgun", class: "Supporter", burstType: "3", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 67, name: "Anne: Miracle Fairy", rarity: "SSR", element: "Wind", weapon: "Rocket Launcher", class: "Supporter", burstType: "2", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 167, name: "Arcana", rarity: "SSR", element: "Electric", weapon: "Rocket Launcher", class: "Supporter", burstType: "2", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 205, name: "Arcana: Fortune Mate", rarity: "SSR", element: "Fire", weapon: "Shotgun", class: "Attacker", burstType: "2", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 25, name: "Aria", rarity: "SSR", element: "Water", weapon: "Minigun", class: "Attacker", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 131, name: "Asuka Shikinami Langley", rarity: "SSR", element: "Fire", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 150, name: "Asuka Shikinami Langley: Wille", rarity: "SSR", element: "Wind", weapon: "Minigun", class: "Attacker", burstType: "3", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 120, name: "Bay", rarity: "SSR", element: "Fire", weapon: "Rocket Launcher", class: "Defender", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 178, name: "Bay (Treasure)", rarity: "SSR", element: "Fire", weapon: "Rocket Launcher", class: "Defender", burstType: "2", manufacturer: "Tetra", hasTreasure: true},
  {unitId: 40, name: "Belorta", rarity: "SR", element: "Electric", weapon: "Rocket Launcher", class: "Attacker", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 80, name: "Biscuit", rarity: "SSR", element: "Electric", weapon: "Rocket Launcher", class: "Supporter", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 86, name: "Blanc", rarity: "SSR", element: "Wind", weapon: "Assault Rifle", class: "Defender", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 162, name: "Bready", rarity: "SSR", element: "Water", weapon: "Sniper Rifle", class: "Attacker", burstType: "3", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 6, name: "Brid", rarity: "SSR", element: "Water", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 192, name: "Brid: Silent Track", rarity: "SSR", element: "Fire", weapon: "Shotgun", class: "Supporter", burstType: "2", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 14, name: "Centi", rarity: "SSR", element: "Iron", weapon: "Rocket Launcher", class: "Defender", burstType: "2", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 199, name: "Centi (Treasure)", rarity: "SSR", element: "Iron", weapon: "Rocket Launcher", class: "Defender", burstType: "2", manufacturer: "Missilis", hasTreasure: true},
  {unitId: 190, name: "Chime", rarity: "SSR", element: "Iron", weapon: "SMG", class: "Supporter", burstType: "2", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 201, name: "Chisato Nishikigi", rarity: "SSR", element: "Iron", weapon: "SMG", class: "Attacker", burstType: "3", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 139, name: "Cinderella", rarity: "SSR", element: "Electric", weapon: "Rocket Launcher", class: "Defender", burstType: "3", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 186, name: "Claire Redfield", rarity: "SR", element: "Electric", weapon: "Rocket Launcher", class: "Supporter", burstType: "1", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 126, name: "Clay", rarity: "SSR", element: "Electric", weapon: "SMG", class: "Supporter", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 74, name: "Cocoa", rarity: "SSR", element: "Fire", weapon: "Sniper Rifle", class: "Supporter", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 16, name: "Crow", rarity: "SSR", element: "Fire", weapon: "SMG", class: "Defender", burstType: "3", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 121, name: "Crown", rarity: "SSR", element: "Iron", weapon: "Minigun", class: "Defender", burstType: "2", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 163, name: "Crust", rarity: "SSR", element: "Water", weapon: "Rocket Launcher", class: "Supporter", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 83, name: "D", rarity: "SSR", element: "Wind", weapon: "SMG", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 116, name: "D: Killer Wife", rarity: "SSR", element: "Fire", weapon: "Sniper Rifle", class: "Supporter", burstType: "1", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 35, name: "Delta", rarity: "SR", element: "Wind", weapon: "Sniper Rifle", class: "Defender", burstType: "2", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 187, name: "Delta: Ninja Thief", rarity: "SSR", element: "Water", weapon: "Minigun", class: "Defender", burstType: "2", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 8, name: "Diesel", rarity: "SSR", element: "Wind", weapon: "Minigun", class: "Defender", burstType: "2", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 149, name: "Diesel (Treasure)", rarity: "SSR", element: "Wind", weapon: "Minigun", class: "Defender", burstType: "2", manufacturer: "Elysion", hasTreasure: true},
  {unitId: 193, name: "Diesel: Winter Sweets", rarity: "SSR", element: "Fire", weapon: "Rocket Launcher", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 43, name: "Dolla", rarity: "SSR", element: "Wind", weapon: "Sniper Rifle", class: "Supporter", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 84, name: "Dorothy", rarity: "SSR", element: "Water", weapon: "Assault Rifle", class: "Supporter", burstType: "1", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 173, name: "Dorothy: Serendipity", rarity: "SSR", element: "Water", weapon: "Shotgun", class: "Attacker", burstType: "3", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 15, name: "Drake", rarity: "SSR", element: "Fire", weapon: "Shotgun", class: "Attacker", burstType: "3", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 159, name: "Drake (Treasure)", rarity: "SSR", element: "Fire", weapon: "Shotgun", class: "Attacker", burstType: "3", manufacturer: "Missilis", hasTreasure: true},
  {unitId: 204, name: "E.H.", rarity: "SSR", element: "Wind", weapon: "SMG", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 129, name: "Ein", rarity: "SSR", element: "Electric", weapon: "Sniper Rifle", class: "Attacker", burstType: "3", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 115, name: "Elegg", rarity: "SSR", element: "Electric", weapon: "Minigun", class: "Supporter", burstType: "2", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 174, name: "Elegg: Boom and Shock", rarity: "SSR", element: "Water", weapon: "Minigun", class: "Attacker", burstType: "3", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 117, name: "Emilia", rarity: "SSR", element: "Water", weapon: "Rocket Launcher", class: "Attacker", burstType: "3", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 1, name: "Emma", rarity: "SSR", element: "Fire", weapon: "Minigun", class: "Supporter", burstType: "1", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 179, name: "Emma: Tactical Upgrade", rarity: "SSR", element: "Fire", weapon: "Minigun", class: "Supporter", burstType: "1", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 24, name: "Epinel", rarity: "SSR", element: "Wind", weapon: "SMG", class: "Attacker", burstType: "3", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 38, name: "Ether", rarity: "SR", element: "Electric", weapon: "Shotgun", class: "Defender", burstType: "1", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 9, name: "Eunhwa", rarity: "SSR", element: "Fire", weapon: "Sniper Rifle", class: "Attacker", burstType: "2", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 180, name: "Eunhwa: Tactical Upgrade", rarity: "SSR", element: "Fire", weapon: "Sniper Rifle", class: "Attacker", burstType: "2", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 170, name: "Eve", rarity: "SSR", element: "Iron", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 32, name: "Exia", rarity: "SSR", element: "Electric", weapon: "Sniper Rifle", class: "Supporter", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 153, name: "Exia (Treasure)", rarity: "SSR", element: "Electric", weapon: "Sniper Rifle", class: "Supporter", burstType: "1", manufacturer: "Tetra", hasTreasure: true},
  {unitId: 142, name: "Flora", rarity: "SSR", element: "Electric", weapon: "Minigun", class: "Supporter", burstType: "2", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 42, name: "Folkwang", rarity: "SSR", element: "Water", weapon: "Assault Rifle", class: "Defender", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 20, name: "Frima", rarity: "SSR", element: "Iron", weapon: "Sniper Rifle", class: "Supporter", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 154, name: "Frima (Treasure)", rarity: "SSR", element: "Iron", weapon: "Sniper Rifle", class: "Supporter", burstType: "1", manufacturer: "Tetra", hasTreasure: true},
  {unitId: 140, name: "Grave", rarity: "SSR", element: "Fire", weapon: "Assault Rifle", class: "Supporter", burstType: "2", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 10, name: "Guillotine", rarity: "SSR", element: "Electric", weapon: "Minigun", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 144, name: "Guillotine: Winter Slayer", rarity: "SSR", element: "Water", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 72, name: "Guilty", rarity: "SSR", element: "Wind", weapon: "Shotgun", class: "Attacker", burstType: "2", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 30, name: "Harran", rarity: "SSR", element: "Electric", weapon: "Sniper Rifle", class: "Attacker", burstType: "3", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 47, name: "Helm", rarity: "SSR", element: "Water", weapon: "Sniper Rifle", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 157, name: "Helm (Treasure)", rarity: "SSR", element: "Water", weapon: "Sniper Rifle", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: true},
  {unitId: 97, name: "Helm: Aquamarine", rarity: "SSR", element: "Iron", weapon: "Assault Rifle", class: "Attacker", burstType: "2", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 79, name: "Himeno", rarity: "SR", element: "Wind", weapon: "Sniper Rifle", class: "Supporter", burstType: "2", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 56, name: "iDoll Flower", rarity: "R", element: "Wind", weapon: "Rocket Launcher", class: "Defender", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 57, name: "iDoll Ocean", rarity: "R", element: "Water", weapon: "SMG", class: "Supporter", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 62, name: "iDoll Sun", rarity: "R", element: "Iron", weapon: "Assault Rifle", class: "Supporter", burstType: "3", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 44, name: "Isabel", rarity: "SSR", element: "Electric", weapon: "Shotgun", class: "Attacker", burstType: "3", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 69, name: "Jackal", rarity: "SSR", element: "Iron", weapon: "Rocket Launcher", class: "Defender", burstType: "1", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 184, name: "Jill Valentine", rarity: "SSR", element: "Electric", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 13, name: "Julia", rarity: "SSR", element: "Iron", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 177, name: "Julia (Treasure)", rarity: "SSR", element: "Iron", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Missilis", hasTreasure: true},
  {unitId: 168, name: "K", rarity: "SSR", element: "Electric", weapon: "SMG", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 122, name: "Kilo", rarity: "SSR", element: "Fire", weapon: "Minigun", class: "Defender", burstType: "3", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 203, name: "Kurumi", rarity: "SR", element: "Iron", weapon: "Assault Rifle", class: "Supporter", burstType: "1", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 195, name: "Label", rarity: "SSR", element: "Iron", weapon: "Assault Rifle", class: "Defender", burstType: "1", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 46, name: "Laplace", rarity: "SSR", element: "Iron", weapon: "Rocket Launcher", class: "Attacker", burstType: "3", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 156, name: "Laplace (Treasure)", rarity: "SSR", element: "Iron", weapon: "Rocket Launcher", class: "Attacker", burstType: "3", manufacturer: "Missilis", hasTreasure: true},
  {unitId: 112, name: "Leona", rarity: "SSR", element: "Water", weapon: "Shotgun", class: "Supporter", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 189, name: "Liberalio", rarity: "SSR", element: "Wind", weapon: "Sniper Rifle", class: "Attacker", burstType: "3", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 169, name: "Lily", rarity: "SR", element: "Wind", weapon: "SMG", class: "Supporter", burstType: "2", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 45, name: "Liter", rarity: "SSR", element: "Iron", weapon: "SMG", class: "Supporter", burstType: "1", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 164, name: "Little Mermaid (Siren)", rarity: "SSR", element: "Wind", weapon: "SMG", class: "Supporter", burstType: "1", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 22, name: "Ludmilla", rarity: "SSR", element: "Water", weapon: "SMG", class: "Defender", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 108, name: "Ludmilla: Winter Owner", rarity: "SSR", element: "Water", weapon: "Minigun", class: "Attacker", burstType: "3", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 48, name: "Maiden", rarity: "SSR", element: "Electric", weapon: "Shotgun", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 143, name: "Maiden: Ice Rose", rarity: "SSR", element: "Electric", weapon: "Rocket Launcher", class: "Defender", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 78, name: "Makima", rarity: "SSR", element: "Water", weapon: "SMG", class: "Defender", burstType: "2", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 146, name: "Mana", rarity: "SSR", element: "Wind", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 102, name: "Marciana", rarity: "SSR", element: "Iron", weapon: "Shotgun", class: "Supporter", burstType: "2", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 133, name: "Mari Makinami Illustrious", rarity: "SSR", element: "Electric", weapon: "Sniper Rifle", class: "Supporter", burstType: "2", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 21, name: "Mary", rarity: "SSR", element: "Water", weapon: "Shotgun", class: "Supporter", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 89, name: "Mary: Bay Goddess", rarity: "SSR", element: "Water", weapon: "Sniper Rifle", class: "Supporter", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 92, name: "Mast", rarity: "SSR", element: "Electric", weapon: "SMG", class: "Supporter", burstType: "2", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 147, name: "Mast: Romantic Maid", rarity: "SSR", element: "Water", weapon: "Minigun", class: "Supporter", burstType: "2", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 11, name: "Maxwell", rarity: "SSR", element: "Iron", weapon: "Sniper Rifle", class: "Attacker", burstType: "3", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 41, name: "Mica", rarity: "SR", element: "Wind", weapon: "Rocket Launcher", class: "Supporter", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 110, name: "Mica: Snow Buddy", rarity: "SSR", element: "Iron", weapon: "SMG", class: "Supporter", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 36, name: "Mihara", rarity: "SR", element: "Water", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 165, name: "Mihara: Bonding Chain", rarity: "SSR", element: "Fire", weapon: "Minigun", class: "Attacker", burstType: "3", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 49, name: "Milk", rarity: "SSR", element: "Water", weapon: "Sniper Rifle", class: "Attacker", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 158, name: "Milk (Treasure)", rarity: "SSR", element: "Water", weapon: "Sniper Rifle", class: "Attacker", burstType: "1", manufacturer: "Tetra", hasTreasure: true},
  {unitId: 183, name: "Milk: Blooming Bunny", rarity: "SSR", element: "Iron", weapon: "Sniper Rifle", class: "Attacker", burstType: "3", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 5, name: "Miranda", rarity: "SSR", element: "Fire", weapon: "SMG", class: "Supporter", burstType: "1", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 160, name: "Miranda (Treasure)", rarity: "SSR", element: "Fire", weapon: "SMG", class: "Supporter", burstType: "1", manufacturer: "Elysion", hasTreasure: true},
  {unitId: 134, name: "Misato Katsuragi", rarity: "SR", element: "Iron", weapon: "SMG", class: "Supporter", burstType: "1", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 68, name: "Modernia", rarity: "SSR", element: "Fire", weapon: "Minigun", class: "Attacker", burstType: "3", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 113, name: "Moran", rarity: "SSR", element: "Electric", weapon: "Assault Rifle", class: "Defender", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 197, name: "Moran (Treasure)", rarity: "SSR", element: "Electric", weapon: "Assault Rifle", class: "Defender", burstType: "1", manufacturer: "Tetra", hasTreasure: true},
  {unitId: 166, name: "Mori", rarity: "SSR", element: "Wind", weapon: "Assault Rifle", class: "Defender", burstType: "2", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 37, name: "N102", rarity: "SR", element: "Water", weapon: "Rocket Launcher", class: "Supporter", burstType: "1", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 103, name: "Naga", rarity: "SSR", element: "Electric", weapon: "Shotgun", class: "Supporter", burstType: "2", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 188, name: "Nayuta", rarity: "SSR", element: "Wind", weapon: "SMG", class: "Supporter", burstType: "2", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 34, name: "Neon", rarity: "SR", element: "Fire", weapon: "Shotgun", class: "Supporter", burstType: "1", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 90, name: "Neon: Blue Ocean", rarity: "SSR", element: "Water", weapon: "Minigun", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 91, name: "Nero", rarity: "SSR", element: "Fire", weapon: "SMG", class: "Defender", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 65, name: "Neve", rarity: "SR", element: "Water", weapon: "Shotgun", class: "Attacker", burstType: "3", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 81, name: "Nihilister", rarity: "SSR", element: "Fire", weapon: "Sniper Rifle", class: "Attacker", burstType: "2", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 31, name: "Noah", rarity: "SSR", element: "Wind", weapon: "Rocket Launcher", class: "Defender", burstType: "2", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 87, name: "Noir", rarity: "SSR", element: "Wind", weapon: "Shotgun", class: "Attacker", burstType: "3", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 26, name: "Noise", rarity: "SSR", element: "Electric", weapon: "Rocket Launcher", class: "Supporter", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 50, name: "Novel", rarity: "SSR", element: "Iron", weapon: "SMG", class: "Defender", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 101, name: "Pascal", rarity: "SR", element: "Iron", weapon: "Rocket Launcher", class: "Supporter", burstType: "1", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 51, name: "Pepper", rarity: "SSR", element: "Wind", weapon: "Shotgun", class: "Supporter", burstType: "1", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 137, name: "Phantom", rarity: "SSR", element: "Water", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 4, name: "Poli", rarity: "SSR", element: "Water", weapon: "Shotgun", class: "Defender", burstType: "2", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 175, name: "Poli (Treasure)", rarity: "SSR", element: "Water", weapon: "Shotgun", class: "Defender", burstType: "2", manufacturer: "Elysion", hasTreasure: true},
  {unitId: 77, name: "Power", rarity: "SSR", element: "Fire", weapon: "Rocket Launcher", class: "Attacker", burstType: "3", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 2, name: "Privaty", rarity: "SSR", element: "Water", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 198, name: "Privaty (Treasure)", rarity: "SSR", element: "Water", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: true},
  {unitId: 114, name: "Privaty: Unkind Maid", rarity: "SSR", element: "Electric", weapon: "Shotgun", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 58, name: "Product 08", rarity: "R", element: "Electric", weapon: "Sniper Rifle", class: "Supporter", burstType: "1", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 63, name: "Product 12", rarity: "R", element: "Fire", weapon: "Minigun", class: "Attacker", burstType: "3", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 60, name: "Product 23", rarity: "R", element: "Wind", weapon: "Shotgun", class: "Supporter", burstType: "2", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 73, name: "Quency", rarity: "SSR", element: "Electric", weapon: "SMG", class: "Supporter", burstType: "2", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 136, name: "Quency: Escape Queen", rarity: "SSR", element: "Water", weapon: "SMG", class: "Attacker", burstType: "3", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 105, name: "Quiry", rarity: "SSR", element: "Wind", weapon: "Rocket Launcher", class: "Supporter", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 119, name: "Ram", rarity: "SR", element: "Wind", weapon: "Sniper Rifle", class: "Defender", burstType: "1", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 33, name: "Rapi", rarity: "SR", element: "Fire", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 145, name: "Rapi: Red Hood", rarity: "SSR", element: "Fire", weapon: "Minigun", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 52, name: "Rapunzel", rarity: "SSR", element: "Iron", weapon: "Rocket Launcher", class: "Supporter", burstType: "1", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 141, name: "Rapunzel: Pure Grace", rarity: "SSR", element: "Iron", weapon: "Sniper Rifle", class: "Defender", burstType: "1", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 171, name: "Raven", rarity: "SSR", element: "Iron", weapon: "Rocket Launcher", class: "Attacker", burstType: "3", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 109, name: "Red Hood", rarity: "SSR", element: "Iron", weapon: "Sniper Rifle", class: "Attacker", burstType: "All", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 85, name: "Rei", rarity: "SSR", element: "Water", weapon: "SMG", class: "Defender", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 132, name: "Rei Ayanami", rarity: "SSR", element: "Fire", weapon: "Minigun", class: "Attacker", burstType: "3", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 151, name: "Rei Ayanami (Tentative Name)", rarity: "SSR", element: "Wind", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 118, name: "Rem", rarity: "SSR", element: "Water", weapon: "Minigun", class: "Supporter", burstType: "2", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 88, name: "Rosanna", rarity: "SSR", element: "Electric", weapon: "Minigun", class: "Attacker", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 128, name: "Rosanna: Chic Ocean", rarity: "SSR", element: "Wind", weapon: "Assault Rifle", class: "Supporter", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 135, name: "Rouge", rarity: "SSR", element: "Electric", weapon: "Sniper Rifle", class: "Supporter", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 138, name: "Rumani", rarity: "SSR", element: "Fire", weapon: "Rocket Launcher", class: "Defender", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 53, name: "Rupee", rarity: "SSR", element: "Iron", weapon: "Assault Rifle", class: "Attacker", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 66, name: "Rupee: Winter Shopper", rarity: "SSR", element: "Electric", weapon: "Assault Rifle", class: "Defender", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 82, name: "Sakura", rarity: "SSR", element: "Fire", weapon: "Sniper Rifle", class: "Supporter", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 152, name: "Sakura Suzuhara", rarity: "SR", element: "Water", weapon: "SMG", class: "Supporter", burstType: "1", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 127, name: "Sakura: Bloom in Summer", rarity: "SSR", element: "Wind", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 29, name: "Scarlet", rarity: "SSR", element: "Electric", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 111, name: "Scarlet: Black Shadow", rarity: "SSR", element: "Wind", weapon: "Rocket Launcher", class: "Attacker", burstType: "3", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 3, name: "Signal", rarity: "SSR", element: "Fire", weapon: "SMG", class: "Attacker", burstType: "2", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 71, name: "Sin", rarity: "SSR", element: "Electric", weapon: "Assault Rifle", class: "Defender", burstType: "2", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 28, name: "Snow White", rarity: "SSR", element: "Iron", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 194, name: "Snow White: Heavy Arms", rarity: "SSR", element: "Water", weapon: "Sniper Rifle", class: "Attacker", burstType: "3", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 106, name: "Snow White: Innocent Days", rarity: "SSR", element: "Iron", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Pilgrim", hasTreasure: false},
  {unitId: 75, name: "Soda", rarity: "SSR", element: "Fire", weapon: "Minigun", class: "Supporter", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 124, name: "Soda: Twinkling Bunny", rarity: "SSR", element: "Iron", weapon: "Shotgun", class: "Attacker", burstType: "3", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 64, name: "Soldier EG", rarity: "R", element: "Electric", weapon: "Assault Rifle", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 61, name: "Soldier FA", rarity: "R", element: "Iron", weapon: "Shotgun", class: "Defender", burstType: "2", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 59, name: "Soldier OW", rarity: "R", element: "Fire", weapon: "SMG", class: "Supporter", burstType: "1", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 7, name: "Soline", rarity: "SSR", element: "Iron", weapon: "SMG", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 191, name: "Soline: Frost Ticket", rarity: "SSR", element: "Water", weapon: "Shotgun", class: "Supporter", burstType: "1", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 172, name: "Sora", rarity: "SSR", element: "Wind", weapon: "Rocket Launcher", class: "Supporter", burstType: "1", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 18, name: "Sugar", rarity: "SSR", element: "Iron", weapon: "Shotgun", class: "Attacker", burstType: "3", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 202, name: "Takina Inoue", rarity: "SSR", element: "Iron", weapon: "Sniper Rifle", class: "Supporter", burstType: "2", manufacturer: "Abnormal", hasTreasure: false},
  {unitId: 104, name: "Tia", rarity: "SSR", element: "Iron", weapon: "Rocket Launcher", class: "Defender", burstType: "1", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 107, name: "Tove", rarity: "SSR", element: "Water", weapon: "Assault Rifle", class: "Supporter", burstType: "1", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 176, name: "Tove (Treasure)", rarity: "SSR", element: "Water", weapon: "Assault Rifle", class: "Supporter", burstType: "1", manufacturer: "Missilis", hasTreasure: true},
  {unitId: 161, name: "Trina", rarity: "SSR", element: "Electric", weapon: "Rocket Launcher", class: "Supporter", burstType: "2", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 123, name: "Trony", rarity: "SSR", element: "Fire", weapon: "Sniper Rifle", class: "Attacker", burstType: "3", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 196, name: "Velvet", rarity: "SSR", element: "Wind", weapon: "Sniper Rifle", class: "Supporter", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 54, name: "Vesti", rarity: "SSR", element: "Water", weapon: "Rocket Launcher", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 181, name: "Vesti: Tactical Upgrade", rarity: "SSR", element: "Fire", weapon: "Rocket Launcher", class: "Attacker", burstType: "3", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 70, name: "Viper", rarity: "SSR", element: "Water", weapon: "Shotgun", class: "Attacker", burstType: "2", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 155, name: "Viper (Treasure)", rarity: "SSR", element: "Water", weapon: "Shotgun", class: "Attacker", burstType: "2", manufacturer: "Tetra", hasTreasure: true},
  {unitId: 27, name: "Volume", rarity: "SSR", element: "Wind", weapon: "SMG", class: "Attacker", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 23, name: "Yan", rarity: "SSR", element: "Fire", weapon: "Rocket Launcher", class: "Supporter", burstType: "1", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 55, name: "Yulha", rarity: "SSR", element: "Fire", weapon: "Sniper Rifle", class: "Attacker", burstType: "3", manufacturer: "Tetra", hasTreasure: false},
  {unitId: 12, name: "Yuni", rarity: "SSR", element: "Fire", weapon: "Rocket Launcher", class: "Defender", burstType: "2", manufacturer: "Missilis", hasTreasure: false},
  {unitId: 130, name: "Zwei", rarity: "SSR", element: "Electric", weapon: "Shotgun", class: "Supporter", burstType: "1", manufacturer: "Elysion", hasTreasure: false},
  {unitId: 200, name: "Zwei (Treasure)", rarity: "SSR", element: "Electric", weapon: "Shotgun", class: "Supporter", burstType: "1", manufacturer: "Elysion", hasTreasure: true}
];
